server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/user
            - Method=GET
          filters:
            - SetPath=/api/user

        - id: artist-service
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/artist
            - Method=GET
          filters:
            - SetPath=/api/artist

        - id: album-service
          uri: http://${ALBUM_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/album
            - Method=GET
          filters:
            - SetPath=/api/album

        - id: playlist-service
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/playlist
            - Method=GET
          filters:
            - SetPath=/api/playlist

