server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  #security:
  # oauth2:
  #   client:
  #     registration:
  #       google:
  #         client-id: ${GOOGLE_CLIENT_ID}
  #         client-secret: ${GOOGLE_CLIENT_SECRET}
  #         scope: openid,profile,email
  #   resourceserver:
  #     jwt:
  #       issuer-uri: https://accounts.google.com
  #       jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/user
            - Method=GET,POST,PUT,DELETE
          filters:
            - SetPath=/api/users

        - id: artist-service
          uri: http://${ARTIST_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/artist
            - Method=GET,POST
          filters:
            - SetPath=/api/artists

        - id: album-service
          uri: http://${ALBUM_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/album
            - Method=GET,POST
          filters:
            - SetPath=/api/albums

        - id: playlist-service
          uri: http://${PLAYLIST_SERVICE_BASEURL:localhost:8084}
          predicates:
            - Path=/playlist
            - Method=GET,POST
          filters:
            - SetPath=/api/playlists