name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04 # Gebruik een stabiele Ubuntu-versie

    steps:
    # Stap 1: Checkout de code
    - name: Checkout code
      uses: actions/checkout@v3

    # Stap 2: Verwijder oude Docker-versies
    - name: Remove old Docker versions
      run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
        sudo apt-get autoremove -y
        sudo apt-get clean

    # Stap 3: Voeg de Docker Repository Toe
    - name: Set up Docker repository
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update

    # Stap 4: Herstel vastgezette pakketten
    - name: Resolve held packages
      run: |
        sudo apt-mark unhold containerd.io || true
        sudo apt-get update

    # Stap 5: Installeer Docker en Docker Compose
    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
        docker --version

    # Stap 6: Bouw de Docker Images
    - name: Build Docker Images
      run: |
        docker-compose -f docker-compose.yml build

    # Stap 7: Deploy de Containers
    - name: Deploy Containers
      run: |
        docker-compose down || true
        docker-compose up -d
